site_name: Tuni Builds
site_url: https://builds.altuni.dev/keyboards

#nav:
#  - Home: index.md
#  - About: about.md

theme:
  name: material
  #favicon: assets/favicon.png
  #logo: assets/logo.png
  font:
    text: Noto Sans
    code: Fira Code
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: amber

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: amber

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: amber
  
  #features:
  #  - navigation.footer
  #  - header.autohide

extra:
  generator: false
  #social:
  # - icon: fontawesome/brands/twitter
  #   link: https://twitter.com
  #   name: Tuni on Twitter
